language: bash

env:
    global:
      - CXX=g++-4.8
      - QEMU_VER=v2.9.1
      - DOCKER_REPO=meyskens/disatch.sh-dashboard
    matrix:
      - ARCH=amd64 ARCHREPO=amd64   QEMU_ARCH=x86_64
      - ARCH=armhf ARCHREPO=arm32v7 QEMU_ARCH=arm    
      - ARCH=arm64 ARCHREPO=arm64v8 QEMU_ARCH=aarch64
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo apt-get -y install qemu qemu-user-static qemu-user binfmt-support
  - docker run --rm --privileged multiarch/qemu-user-static:register
os:
- linux
script:
- wget -N https://github.com/multiarch/qemu-user-static/releases/download/$QEMU_VER/x86_64_qemu-${QEMU_ARCH}-static.tar.gz
- tar -xvf x86_64_qemu-${QEMU_ARCH}-static.tar.gz
- docker build -t $DOCKER_REPO:$ARCH-$TRAVIS_COMMIT --build-arg ARCH="$ARCH" --build-arg QEMU_ARCH="$QEMU_ARCH" ./

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
  - echo "$HARBOR_PASSWORD" | docker login -u "$HARBOR_USERNAME" --password-stdin harbor.dispatch.sh
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker push $DOCKER_REPO:$ARCH-$TRAVIS_COMMIT ; fi
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker tag $DOCKER_REPO:$ARCH-$TRAVIS_COMMIT $DOCKER_REPO:$ARCH-master; docker push $DOCKER_REPO:$ARCH-master ; fi
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_TAG" != "" ]; then docker tag $DOCKER_REPO:$ARCH-$TRAVIS_COMMIT $DOCKER_REPO:$ARCH-$TRAVIS_TAG; docker push $DOCKER_REPO:$ARCH-$TRAVIS_TAG ; fi
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$ARCH" == "arm64" ]; then docker tag $DOCKER_REPO:$ARCH-$TRAVIS_COMMIT harbor.dispatch.sh/maartje/dispatch-dashboard:$ARCH-$TRAVIS_COMMIT; docker push harbor.dispatch.sh/maartje/dispatch-dashboard:$ARCH-$TRAVIS_COMMIT ; fi